# Generated by Django 3.0 on 2020-04-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drbotapp', '0002_auto_20200421_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='applob',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
