# Generated by Django 3.0 on 2020-04-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drbotapp', '0005_remove_rparobotconfig_botjson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rparobotconfig',
            name='botServerID',
            field=models.CharField(max_length=100),
        ),
    ]
