# Generated by Django 3.0 on 2020-04-26 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drbotapp', '0006_auto_20200426_0914'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tblJobsch',
        ),
        migrations.DeleteModel(
            name='tbltrans',
        ),
    ]
