# Generated by Django 3.0 on 2020-04-26 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drbotapp', '0007_auto_20200426_0927'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='appinfo',
            new_name='rpaappinfo',
        ),
        migrations.RenameModel(
            old_name='botmachine',
            new_name='rpabotmachine',
        ),
    ]
