# Generated by Django 3.0 on 2020-04-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drbotapp', '0008_auto_20200426_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpabotmachine',
            name='RPAServerID',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
