# Generated by Django 3.0 on 2020-05-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drbotapp', '0009_rpabotmachine_rpaserverid'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpabotmachine',
            name='NumberofBots',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
