# Generated by Django 3.0 on 2020-04-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tblConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botname', models.CharField(max_length=100)),
                ('botdescription', models.CharField(max_length=100)),
                ('application', models.CharField(max_length=30)),
            ],
        ),
    ]
