# Generated by Django 3.0 on 2020-04-17 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drbotapp', '0004_userprofileinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='rofile_pic',
            new_name='profile_pic',
        ),
    ]
