# Generated by Django 3.0 on 2020-04-17 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drbotapp', '0009_auto_20200417_1058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
