# Generated by Django 3.0 on 2020-04-21 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drbotapp', '0011_appconfig_contact_userprofileinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
